Hotel/Hotel/Controllers/ClientController.cs
using Hotel.Data;
using Hotel.Filters;
using Hotel.Models;
using Microsoft.AspNetCore.Mvc;

namespace Hotel.Controllers  
{
	[AuthFilter]
	public class ClientController : Controller
    {
        private readonly AppDbcontext _db;

        public ClientController(AppDbcontext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Client> objListClients = _db.Clients;
            return View(objListClients);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Client model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            _db.Clients.Add(model);
            _db.SaveChanges();
            return RedirectToAction("Index");
		}

		[HttpGet]
        public IActionResult Edit(int id)
        {
            Client client = _db.Clients.SingleOrDefault(x => x.Id == id);
			if (client == null)
            {
                return RedirectToAction("Index");
            }
            return View(client);
        }

        [HttpPost]
        public IActionResult Edit(Client model)
        { 
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            _db.Clients.Update(model);
            _db.SaveChanges();
			return RedirectToAction("Index");
		}
		public IActionResult Delete(int id)
		{

			//намира от базата данни етаж който има същото id като подаденото id
			Client client = _db.Clients.SingleOrDefault(x => x.Id == id);
			if (client != null)
			{
				_db.Remove(client);
				_db.SaveChanges();
			}

			return RedirectToAction("Index");

		}

        public IActionResult Details(int id) {
            Client client = _db.Clients.SingleOrDefault(x => x.Id == id);
            if (client == null)
            {
                return RedirectToAction("Index");
            }

           
            return View(client);
        }
	}
}

Hotel/Hotel/Controllers/FloorController.cs
using Hotel.Data;
using Hotel.Filters;
using Hotel.Models;
using Hotel.Models.View_Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Controllers
{
    [AuthFilter]
    public class FloorController : Controller
    {
        private readonly AppDbcontext _db;
        public FloorController(AppDbcontext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Floor> objListFloors = _db.Floors;
            return View(objListFloors);
        }

        [HttpGet]
        [RoleFilter]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Floor model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            _db.Floors.Add(model);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Floor floor = _db.Floors.SingleOrDefault(x => x.Id == id);
            if (floor == null)
            {
                return RedirectToAction("Index");
            }
            return View(floor);

        }

        [HttpPost]
        public IActionResult Edit(Floor model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            _db.Floors.Update(model);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            //намира от базата данни етаж който има същото id като подаденото id
            Floor floor = _db.Floors.SingleOrDefault(x => x.Id == id);
            if (floor != null)
            {
                _db.Remove(floor);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            List<Room> rooms = _db.Room.Include(r => r.RoomType).Include(r => r.Floor).Where(r => r.FloorId == id).ToList();

			List<FloorRoomVM> roomsVM = new List<FloorRoomVM>();
            ViewBag.FloorLvl = _db.Floors.FirstOrDefault(f => f.Id == id).Level;
			if (rooms.Count > 0)
			{
				DateTime now = DateTime.Now.Date;
				foreach (Room room in rooms)
				{
					FloorRoomVM vM = new FloorRoomVM();
					List<Reservation> reservations = _db.Reservations.Where(r => r.Room_id == room.Id).ToList();
					Reservation closestReservation = _db.Reservations
						.Include(r => r.Client)
						.Include(r => r.Room)
						.Include(r => r.ReservationStatus)
						.Where(r => r.Room_id == room.Id && r.RservationStart.Date <= now && r.RservationEnd.Date >= now)
						.OrderBy(r => r.RservationStart)
						.FirstOrDefault();
					if (closestReservation == null)
					{
						vM.Status = "Free";
					}
					else
					{
						vM.Status = closestReservation.ReservationStatus.Title.ToString();
					}
					vM.Room = room;
					roomsVM.Add(vM);
				}
			}
			
            return View(roomsVM);
        }
    }
}

Hotel/Hotel/Controllers/RoomController.cs
using Hotel.Data;
using Hotel.Filters;
using Hotel.Models;
using Hotel.Models.View_Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Controllers
{
    [AuthFilter]
    public class RoomController : Controller
    {
        private readonly AppDbcontext _db;
        public RoomController(AppDbcontext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Room> objListRoom = _db.Room.Include(r => r.RoomType).Include(r=> r.Floor);
            return View(objListRoom);
        }

        [HttpGet]
        [RoleFilter]
        public IActionResult Create()
        {


            RoomVM model = new RoomVM();
            model.floors = _db.Floors.ToList();
            model.roomTypes = _db.RoomType.ToList();



            return View(model);
        }

        [HttpPost]
        [RoleFilter]
        public IActionResult Create(RoomVM model)
        {
            if (!ModelState.IsValid)
            {
               

                model.floors = _db.Floors.ToList();
                model.roomTypes = _db.RoomType.ToList();


                return View(model);
            }
            Room room = new Room();
            room.RoomNumber = model.RoomNumber;
            room.RoomTypeId = model.RoomTypeId;
            room.RoomType = _db.RoomType.SingleOrDefault(rt => rt.Id == model.RoomTypeId);

            int floor_id = model.FloorId;
            room.FloorId = floor_id;
            room.Floor = _db.Floors.SingleOrDefault(rt => rt.Id == floor_id);

            _db.Room.Add(room);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Room room = _db.Room.Include(r=>r.Floor).SingleOrDefault(x => x.Id == id);
            if (room == null)
            {
                return RedirectToAction("Index");
            }

            RoomVM roomVM = new RoomVM();
            roomVM.FloorId = room.FloorId;
            roomVM.floors = _db.Floors.ToList();
            roomVM.roomTypes = _db.RoomType.ToList();
            roomVM.RoomNumber = room.RoomNumber;
            roomVM.RoomTypeId = room.RoomTypeId;
            return View(roomVM);

        }

        [HttpPost]
        public IActionResult Edit(RoomVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Room room = new Room();
            room.FloorId = model.FloorId;
            room.RoomNumber = model.RoomNumber;
            room.RoomTypeId = model.RoomTypeId;
            _db.Room.Update(room);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            Room room = _db.Room.SingleOrDefault(x => x.Id == id);
            if (room != null)
            {
                _db.Remove(room);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Hotel/Hotel/Controllers/UserController.cs
using Hotel.Data;
using Hotel.Filters;
using Hotel.Models.View_Models;
using Hotel.Models;
using Microsoft.AspNetCore.Mvc;

namespace Hotel.Controllers
{

    [AuthFilter]
    public class UserController : Controller
    {
       
            private readonly AppDbcontext _db;
            public UserController(AppDbcontext db)
            {
                _db = db;
            }

            public IActionResult Index()
            {
                IEnumerable<User> users = _db.User;
                return View(users);
            }

            [HttpGet]
            [RoleFilter]
            public IActionResult Create()
            {
                return View();
            }

            [HttpPost]
            public IActionResult Create(User model)
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                _db.User.Add(model);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            [HttpGet]
            public IActionResult Edit(int id)
            {
                User user = _db.User.SingleOrDefault(x => x.Id == id);
                if (user == null)
                {
                    return RedirectToAction("Index");
                }
                return View(user);

            }

            [HttpPost]
            public IActionResult Edit(User model)
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                _db.User.Update(model);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            public IActionResult Delete(int id)
            {
                //намира от базата данни етаж който има същото id като подаденото id
                User user = _db.User.SingleOrDefault(x => x.Id == id);
                if (user != null)
                {
                    _db.Remove(user);
                    _db.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            public IActionResult Details(int id)
            {
                 return View();   
            }
        } 
}

Hotel/Hotel/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hotel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Hotel.styles.css" asp-append-version="true" />
</head>
<body>

    <header class="header">
        <nav class="navbar navbar navbar-toogleable-xl navbar-dark bg-white border-bottom box-shadow mb-3 orientation.vertical">
            <div class="container-fluid">
                 <div class="navbar collapse collapse d-sm-inline-flex justify-content-"> 
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <img src="/images/Logo.png" width="60" height="70"  asp-append-version="true" alt="Home"/>
        </a>
        </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-">
                    <ul class="navbar-nav flex-gcolumn-1 justify-content-center">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Hotel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Hotel/Hotel/Views/Shared/_Layout.cshtml
@{
	var value = this.ViewContext.HttpContext.Session.GetString("loggedUser");
	User loggedUser = null;
	if (value != null)
	{
		loggedUser = Newtonsoft.Json.JsonConvert.DeserializeObject<User>(value);
	}
}
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
	<link rel="apple-touch-icon" sizes="76x76" href="/images/apple-icon.png">
	<link rel="icon" type="image/png" sizes="96x96" href="/images/HomeButton.jpg">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Moonlight manor</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
	<meta name="viewport" content="width=device-width" 

	<!-- Bootstrap core CSS     -->
	<link href="~/css/bootstrap.min.css" rel="stylesheet" />

	<!-- Animation library for notifications   -->
	<link href="~/css/animate.min.css" rel="stylesheet"/>

	<!--  Paper Dashboard core CSS    -->
	<link href="~/css/paper-dashboard.css" rel="stylesheet"/>



	<!--  Fonts and icons     -->
	<link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
	<link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
	<link href="~/css/themify-icons.css" rel="stylesheet">

</head>
<body>

<div class="wrapper">
	<div class="sidebar" data-background-color="white" data-active-color="danger">

	<!--
		Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
		Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
	-->

		<div class="sidebar-wrapper">
			<div class="logo" style="height: 100px; display: flex; justify-content: center; flex-direction: column; ">
				<a class="navbar-brand" asp-area="" asp-controller="Floor" asp-action="Index" 
							style="height: 150px; width: 260px; padding-right: 50px;">
				<img src="/Logo.png" 
							width="220" height="230"  asp-append-version="true" alt="Logo"
							style=" height: 300px;
									width: 200px;
									padding-bottom: 150px;"/>
				</a>
			</div>
				@if (loggedUser != null)
				{
				<ul class="nav">
				
					<li>
						<a class="nav-link text-dark" asp-area="" asp-controller="Floor" asp-action="Index">
							<i class="ti-list-ol"></i>
							<p>Етажи</p>
						</a>
					</li>
					<li>
						<a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">
							<i class="ti-user"></i>
							<p>Клиенти</p>
						</a>
					</li>
					<li>
						<a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Index">
							<i class="ti-check-box"></i>
							<p>Резервации</p>
						</a>
					</li>
						@if (loggedUser.Role == Role.Admin)
						{
							<li>
								<a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="Index">
									<i class="ti-view-list-alt"></i>
									<p>Стаи</p>
								</a>
 							</li>
							<li>
								<a class="nav-link text-dark"  asp-area="" asp-controller="RoomType" asp-action="Index">
									<i class="ti-view-list"></i>
									<p>Видове стаи</p>
								</a>
							</li>

							<li>
								<a class="nav-link text-dark"  asp-area="" asp-controller="User" asp-action="Index">
									<i class="ti-id-badge"></i>
									<p>Потребители</p>
								</a>
							</li>
						}

					<li class="active-pro">
							 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout" style="margin-top: 130px">
								<i class="ti-shift-left"></i>
							<p>Изход</p>
						</a>
					</li>
				</ul>
				}
		</div>
	</div>
		<div class="main-panel">
				<nav class="navbar navbar-default">
					<div class="container-fluid">
						<div class="navbar-header">

						@if (IsSectionDefined("TitleSection"))
						{
							RenderSection("TitleSection", false);
						}
						else
						{
											<title>Hotel</title>
						}
						</div>
					</div>
				</nav>
			<div class="content">

				@RenderBody()
			</div>
		<footer class="footer">
			<div class=""class="container-fluid">
			</div>
				<nav class="pull-left">		
				</nav>
				<div class="copyright pull-right">
					© 2024 All rights reserved "Moonlight manor"
				</div>
		</footer>
	</div>
	</div>

	</div>
</div>
</body>


	<!--   Core JS Files   -->
	<script src="~/js/jquery-1.10.2.js" type="text/javascript"></script>
	<script src="~/js/bootstrap.min.js" type="text/javascript"></script>

	<!--  Checkbox, Radio & Switch Plugins -->
	<script src="~/js/bootstrap-checkbox-radio.js"></script>

	<!--  Charts Plugin -->
	<script src="~/js/chartist.min.js"></script>

	<!--  Notifications Plugin    -->
	<script src="~/js/bootstrap-notify.js"></script>

	<!--  Google Maps Plugin    -->
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

	<!-- Paper Dashboard Core javascript and methods for Demo purpose -->
	<script src="~/js/paper-dashboard.js"></script>

	<!-- Paper Dashboard DEMO methods, don't include it in your project! -->
	<script src="/js/demo.js"></script>


	<script>
		$(document).ready(function(){
			var currentUrl = window.location.href;

			$('.nav li').each(function (){
				var linkUrl = $(this).find('a').attr('href');
				if(currentUrl.endsWith(linkUrl)){
					$(this).addClass('active');
				}else {
					$(this).removeClass('active');
				}
			});
		});
	</script>

<script>
	function confirmDelete(floorId,location){
		var result = window.confirm("Are you sure you want to delete this ");
		if(result){

			window.location.href = location + floorId;
		}
		else{

		}
	}
</script>
 @RenderSection("Scripts", required: false)

</html>