Hotel/Hotel/Controllers/RoomTypeController.cs
using Hotel.Data;
using Hotel.Filters;
using Hotel.Models;
using Microsoft.AspNetCore.Mvc;

namespace Hotel.Controllers
{
	[AuthFilter]
	public class RoomTypeController : Controller
	{
		private readonly AppDbcontext _db;
		public RoomTypeController(AppDbcontext db)
		{
			_db = db;
		}
		public IActionResult Index()
		{
			IEnumerable<RoomType> objListRoomTypes = _db.RoomType;
			return View(objListRoomTypes);
		}

		[HttpGet]
		[RoleFilter]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]

		public IActionResult Create(RoomType model)
		{
			if (!ModelState.IsValid)
			{
				return View(model);
			}
			_db.RoomType.Add(model);
			_db.SaveChanges();
			return RedirectToAction("Index");
		}

        [HttpGet]
		public IActionResult Edit(int id)
		{
			RoomType roomType = _db.RoomType.SingleOrDefault(x => x.Id == id);
			if (roomType == null)
			{
				return RedirectToAction("Index");
			}
			return View(roomType);
			
		}

		[HttpPost]
        public IActionResult Edit(RoomType model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            _db.RoomType.Update(model);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

		public IActionResult Delete(int id)
		{

			//намира от базата данни етаж който има същото id като подаденото id
			RoomType roomtype = _db.RoomType.SingleOrDefault(x => x.Id == id);
			if (roomtype != null)
			{
				_db.Remove(roomtype);
				_db.SaveChanges();
			}

			return RedirectToAction("Index");

		}

		public IActionResult Details(int id)
		{
			RoomType roomtype = _db.RoomType.SingleOrDefault(x => x.Id == id);
			if (roomtype == null)
			{
				return RedirectToAction("Index");
			}


			return View(roomtype);
		}
	}
}

Hotel/Hotel/Views/RoomType/Create.cshtml
@model Hotel.Models.RoomType
@{
    ViewData["Title"] = "Създай нов вид стая";
}
<h4 style="text-align: center">Създай нов вид стая</h4>
<div class="row" style="
        display: flex;
        align-items: center;
        flex-direction: column;">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Title" style="margin: 8px" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" style="margin: 8px" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
           <div class="form-group">
                <label asp-for="Number_of_beds" class="control-label"></label>
                <input asp-for="Number_of_beds" class="form-control" />
                <span asp-validation-for="Number_of_beds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class= "checkbox"
                    <label>
                        <input asp-for="Does_it_have_balcony"/> @Html.DisplayNameFor(model => model.Does_it_have_balcony)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Създай нов вид стая" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div style="text-align: center; padding-left: 25%">
    <a asp-action="Index">Връщане в списъка</a>
</div>

Hotel/Hotel/Views/RoomType/Edit.cshtml
@model Hotel.Models.RoomType
@{
	ViewData["Title"] = "Edit Room types";
}
@section TitleSection {
						 <a class="navbar-brand">
							 Редактиране на вид стая</a>
}
<h4 style="text-align: center">Редактирай вид стая</h4>
<div class="row" style="
        display: flex;
        align-items: center;
        flex-direction: column;">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Title" style="margin: 8px" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" style="margin: 8px" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
           <div class="form-group">
                <label asp-for="Number_of_beds" class="control-label"></label>
                <input asp-for="Number_of_beds" class="form-control" />
                <span asp-validation-for="Number_of_beds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Does_it_have_balcony" /> @Html.DisplayNameFor(model => model.Does_it_have_balcony)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Запазване на промените" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div style="text-align: center; padding-left: 25%">
    <a asp-action="Index">Връщане на списъка</a>
</div>

Hotel/Hotel/Views/RoomType/Index.cshtml
@model IEnumerable<Hotel.Models.RoomType>

@{
    ViewData["Title"] = "Room types";
}
@section TitleSection {
             <a class="navbar-brand">Видове стаи</a>
}
<div class="text-left">
         <a asp-action="Create" asp-controller="RoomType">
             <button type="submit" class="btn btn-info btn-fill btn-wd" style="margin-bottom: 15px;"> 
                 <i class="ti-plus"></i>
                 Създай нов вид стая</button> 
         </a>
</div>
<div class="card">
        <div class="header">
             <h4 class="title">Вид стая</h4>
             <p class="category">Информация за всички видове стаи</p>
        </div>
        <div class="content table-responsive table-full-width">
        <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col" style="text-align: center">
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th scope="col" style="text-align: center">
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th scope="col" style="text-align: center">
                @Html.DisplayNameFor(model => model.Number_of_beds)
            </th>
            <th scope="col" style="text-align: center">
                Има ли тераса
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th scope="col" style="text-align: center;">
                Действия
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var roomType in Model) {
        <tr>
                <td style="text-align: center">
                    @roomType.Title
            </td>
                <td style="text-align: center">
                    @roomType.Description
            </td>
                <td style="text-align: center">
                    @roomType.Number_of_beds
            </td>
                <td style="text-align: center">
                    @roomType.Does_it_have_balcony
            </td>
                <td style="text-align: center">
                    @roomType.Price
            </td>
                <td style="display: flex; justify-content: center;">

                            <a asp-action="Edit" asp-controller="RoomType" asp-route-id="@roomType.Id" style= "margin-right: 5px;">
                                <button type="submit" class="btn btn-success  btn-fill btn-wd"> 
                                    <i class="ti-pencil" style="margin-right:8px"></i>Редактиране
                                </button>
                            </a>
                            <a onclick="confirmDelete(@roomType.Id, '/RoomType/Delete/')" style= "margin-right: 5px;">
                                <button type="submit" class="btn btn-danger   btn-fill btn-wd"> 
                                    <i class="ti-trash" style="margin-right: 8px"></i>Изтрий
                                </button>
                            </a>
                    </td>
        </tr>
}
    </tbody>
</table>
</div>
</div>